### ISSUE TITLE
Many errors occurred during compilation

### ISSUE THREAD

**Issue by gdoupanguoqing** [javagl/cesium-cpp#1]
1>------ Build started: Project: libjpeg-turbo, Configuration: Debug x64 ------
2>------ Build started: Project: cesium-cpp, Configuration: Debug x64 ------
2>NullResourcePreparer.cpp
2>D:\cesium\cesium-cpp\Source\include\CesiumNativeImpl/NullResourcePreparer.h(26): error C3668: 'CesiumCpp::CesiumNativeImpl::NullResourcePreparer::prepareInLoadThread': method with override specifier 'override' did not override any base class methods
2>D:\cesium\cesium-cpp\Source\include\CesiumNativeImpl/NullResourcePreparer.h(35): error C3668: 'CesiumCpp::CesiumNativeImpl::NullResourcePreparer::prepareRasterInLoadThread': method with override specifier 'override' did not override any base class methods
2>D:\cesium\cesium-cpp\Source\include\CesiumNativeImpl/NullResourcePreparer.h(38): error C3668: 'CesiumCpp::CesiumNativeImpl::NullResourcePreparer::prepareRasterInMainThread': method with override specifier 'override' did not override any base class methods
2>TilesTests.cpp
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(117): error C2039: 'ImplicitTraversalInfo': is not a member of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/registerAllTileContentTypes.h(3): note: see declaration of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(117): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(117): error C2143: syntax error: missing ',' before '&'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(118): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(119): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(118): error C2789: 'usingImplicitTiling': an object of const-qualified type must be initialized
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(118): note: see declaration of 'usingImplicitTiling'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(121): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(120): error C2789: 'subtreeLoaded': an object of const-qualified type must be initialized
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(120): note: see declaration of 'subtreeLoaded'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(127): error C2039: 'ImplicitTraversalInfo': is not a member of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/registerAllTileContentTypes.h(3): note: see declaration of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(127): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(127): error C2143: syntax error: missing ',' before '&'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(128): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(129): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(128): error C2789: 'usingImplicitTiling': an object of const-qualified type must be initialized
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(128): note: see declaration of 'usingImplicitTiling'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(132): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(131): error C2789: 'subtreeLoaded': an object of const-qualified type must be initialized
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(131): note: see declaration of 'subtreeLoaded'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(135): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(136): error C2039: 'TileAvailabilityFlags': is not a member of 'CesiumGeometry'
2>D:\cesium\cesium-cpp\extern\cesium-native\CesiumGeometry\include\CesiumGeometry/QuadtreeTileID.h(8): note: see declaration of 'CesiumGeometry'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(136): error C3083: 'TileAvailabilityFlags': the symbol to the left of a '::' must be a type
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(136): error C2039: 'CONTENT_AVAILABLE': is not a member of 'CesiumGeometry'
2>D:\cesium\cesium-cpp\extern\cesium-native\CesiumGeometry\include\CesiumGeometry/QuadtreeTileID.h(8): note: see declaration of 'CesiumGeometry'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(136): error C2065: 'CONTENT_AVAILABLE': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(134): error C2789: 'implicitContentAvailability': an object of const-qualified type must be initialized
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(134): note: see declaration of 'implicitContentAvailability'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(149): error C2039: 'ImplicitTraversalInfo': is not a member of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/registerAllTileContentTypes.h(3): note: see declaration of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(149): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(149): error C2143: syntax error: missing ',' before '&'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(151): error C3083: 'LoadState': the symbol to the left of a '::' must be a type
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(151): error C2039: 'Unloaded': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(151): error C2065: 'Unloaded': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(155): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(156): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(159): error C2039: 'loadContent': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(164): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(165): error C2039: 'loadContent': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(168): error C3083: 'LoadState': the symbol to the left of a '::' must be a type
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(168): error C2039: 'Unloaded': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(168): error C2065: 'Unloaded': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(169): error C3083: 'LoadState': the symbol to the left of a '::' must be a type
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(169): error C2039: 'ContentLoaded': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(169): error C2065: 'ContentLoaded': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(173): error C2039: 'getTileset': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(176): error C3083: 'LoadState': the symbol to the left of a '::' must be a type
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(176): error C2039: 'Unloaded': is not a member of 'Cesium3DTilesSelection::Tile'
2>d:\cesium\cesium-cpp\extern\cesium-native\cesium3dtilesselection\include\cesium3dtilesselection\ViewUpdateResult.h(10): note: see declaration of 'Cesium3DTilesSelection::Tile'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(176): error C2065: 'Unloaded': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(173): error C2660: 'CesiumCpp::TilesTests::waitFor': function does not take 3 arguments
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(80): note: see declaration of 'CesiumCpp::TilesTests::waitFor'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(192): error C2039: 'ImplicitTraversalInfo': is not a member of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/registerAllTileContentTypes.h(3): note: see declaration of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(192): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(192): error C2143: syntax error: missing ',' before '&'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(194): error C2065: 'indentation': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(197): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(199): error C2039: 'ImplicitTraversalInfo': is not a member of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/registerAllTileContentTypes.h(3): note: see declaration of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(199): error C2146: syntax error: missing ';' before identifier 'childInfo'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(200): error C2065: 'implicitInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(199): error C3861: 'childInfo': identifier not found
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(201): error C2065: 'childInfo': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(201): error C2065: 'indentation': undeclared identifier
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(206): error C2039: 'ImplicitTraversalInfo': is not a member of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/registerAllTileContentTypes.h(3): note: see declaration of 'Cesium3DTilesSelection'
2>D:\cesium\cesium-cpp\Source\src\TilesTests\TilesTests.cpp(206): error C3861: 'ImplicitTraversalInfo': identifier not found
2>Utils.cpp
2>D:\cesium\cesium-cpp\Source\include\CesiumNativeImpl/NullResourcePreparer.h(26): error C3668: 'CesiumCpp::CesiumNativeImpl::NullResourcePreparer::prepareInLoadThread': method with override specifier 'override' did not override any base class methods
2>D:\cesium\cesium-cpp\Source\include\CesiumNativeImpl/NullResourcePreparer.h(35): error C3668: 'CesiumCpp::CesiumNativeImpl::NullResourcePreparer::prepareRasterInLoadThread': method with override specifier 'override' did not override any base class methods
2>D:\cesium\cesium-cpp\Source\include\CesiumNativeImpl/NullResourcePreparer.h(38): error C3668: 'CesiumCpp::CesiumNativeImpl::NullResourcePreparer::prepareRasterInMainThread': method with override specifier 'override' did not override any base class methods
2>D:\cesium\cesium-cpp\Source\src\Utils\Utils.cpp(98): error C2039: 'tilesToNoLongerRenderThisFrame': is not a member of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/ViewUpdateResult.h(22): note: see declaration of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\Source\src\Utils\Utils.cpp(100): error C2039: 'tilesLoadingLowPriority': is not a member of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/ViewUpdateResult.h(22): note: see declaration of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\Source\src\Utils\Utils.cpp(103): error C2039: 'tilesLoadingMediumPriority': is not a member of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/ViewUpdateResult.h(22): note: see declaration of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\Source\src\Utils\Utils.cpp(105): error C2039: 'tilesLoadingHighPriority': is not a member of 'Cesium3DTilesSelection::ViewUpdateResult'
2>D:\cesium\cesium-cpp\extern\cesium-native\Cesium3DTilesSelection\include\Cesium3DTilesSelection/ViewUpdateResult.h(22): note: see declaration of 'Cesium3DTilesSelection::ViewUpdateResult'
2>Generating Code...
2>Done building project "cesium-cpp.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 53 up-to-date, 0 skipped ==========

**Comment by javagl** [comment]
This looks like the errors that one would see _before_ the last commit ( https://github.com/javagl/cesium-cpp/commit/4bca6e97c3cd3f567907384f13bc1b36f381bfa1 )

Note that the `cesium-native` dependency in this project is not "versioned" in any way. The `cesium-native` library is constantly undergoing changes, and I'm only occasionally updating `cesium-cpp` accordingly. (All this could be solved in a much cleaner way with Git submodules, but ... let's skip the topic of "dependency handling in C++" for now).

When you check out ...
- the **current** `master` state of `cesium-cpp` and
- the **current** `main` state of `cesium-native`

then you should not see this error.

If you _still_ see this error, we'll have to look at why your local files are different from mine...

**Comment by gdoupanguoqing** [comment]
I successfully compiled using cesium native v0.18.1

**Comment by javagl** [comment]
I'm hesitating on whether to close this issue, or leave it open as a reminder to find a """better""" solution for the actual `cesium-native` dependency. 

This whole project is just a local experiment of mine, to run some tests. Maybe parts of it turn out to be useful for others, but I cannot claim that I'm actively maintaining it, beyond occasional updates based on the latest `cesium-native` state. So... I'll close this issue for now, but will consider adding some proper dependency versioning some time in the future.
